"""
pipeline/invite.py
Invite link generation and token resolution for Meridian.
"""

from pipeline.db import get_supabase_client


def generate_invite_link(workstream_id: str, created_by: str) -> str:
    """
    Create a new invite_links row and return the full invite URL.
    Token is generated by the DB default (gen_random_bytes).
    """
    # TODO: implement — insert into invite_links, return URL
    raise NotImplementedError


def resolve_invite_token(token: str) -> dict | None:
    """
    Look up an active invite token.
    Returns the invite_links row dict, or None if token is invalid/inactive.
    """
    # TODO: implement — query invite_links where token = ? and is_active = true
    raise NotImplementedError


def accept_invite(token: str, user_id: str) -> bool:
    """
    Add a user to the workstream as Viewer after they register/log in via invite link.
    Returns True on success, False if token is invalid.
    """
    # TODO: implement — resolve token, insert into workstream_members with role='viewer'
    raise NotImplementedError
